[package]
name = "rustphorus"
version = "0.1.0"
edition = "2021"

[dependencies]
derivative = "2.2.0"
libc = "0.2.147"
log = "0.4.19"
pretty_env_logger = "0.5.0"
sdl2 = { version = "0.35.2", features = ["image", "ttf"] }
serde = { version = "1.0.181", features = ["derive"] }
serde_json = "1.0.104"
