[package]
name = "rustphorus"
version = "0.1.0"
edition = "2021"

[dependencies]
derivative = "2.2.0"
sdl2 = { version = "0.35.2", features = ["image"] }
serde = { version = "1.0.181", features = ["derive"] }
serde_json = "1.0.104"
